# Generated by Django 3.2.7 on 2021-09-05 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(blank=True, max_length=254, verbose_name='Bill name')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount')),
                ('type', models.CharField(choices=[('misc', 'Miscellaneous')], default='misc', max_length=254, verbose_name='Bill type')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bill',
                'verbose_name_plural': 'Bills',
                'db_table': 'bill_bill',
            },
        ),
        migrations.CreateModel(
            name='BillSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount')),
                ('fulfilled', models.BooleanField(default=False, verbose_name='Fullfilled')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bill.bill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bill Subscriber',
                'verbose_name_plural': 'Bill Subscribers',
                'db_table': 'bill_billsubscriber',
            },
        ),
        migrations.CreateModel(
            name='BillAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(blank=True, max_length=254, verbose_name='Bill attachment name')),
                ('file', models.FileField(upload_to='media/bill/billattachment', verbose_name='File')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='bill.bill')),
            ],
            options={
                'verbose_name': 'Bill Attachment',
                'verbose_name_plural': 'Bill Attachments',
                'db_table': 'bill_billattachment',
            },
        ),
        migrations.AddField(
            model_name='bill',
            name='subscribers',
            field=models.ManyToManyField(through='bill.BillSubscriber', to=settings.AUTH_USER_MODEL),
        ),
    ]
