# Generated by Django 3.2.7 on 2021-10-10 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billattachment',
            name='file',
            field=models.FileField(upload_to='bill/billattachment', verbose_name='File'),
        ),
    ]
