# Generated by Django 3.2.7 on 2021-10-31 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0003_auto_20211026_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billsubscriber',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriber_instances', to='bill.bill'),
        ),
    ]
