# Generated by Django 3.2.7 on 2021-11-10 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bill', '0004_alter_billsubscriber_bill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='subscribers',
        ),
        migrations.AlterField(
            model_name='billsubscriber',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='bill.bill'),
        ),
        migrations.AlterField(
            model_name='billsubscriber',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribed_bills', to=settings.AUTH_USER_MODEL),
        ),
    ]
