# Generated by Django 3.2.7 on 2021-10-10 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='cover_image',
            field=models.FileField(blank=True, null=True, upload_to='event/cover_image', verbose_name='Cover image'),
        ),
    ]
