# Generated by Django 3.2.7 on 2021-09-03 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=254, verbose_name='Name')),
                ('phone', models.CharField(max_length=18, unique=True, verbose_name='Phone')),
                ('email', models.EmailField(max_length=254, null=True, unique=True, verbose_name='Email')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Bio')),
                ('avatar', models.FileField(blank=True, null=True, upload_to='media/user/avatar', verbose_name='Avatar')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
