# Generated by Django 3.2.7 on 2021-09-09 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210906_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='firebase_id',
            field=models.CharField(default='hellloooo', max_length=254, unique=True, verbose_name='Firebase ID'),
            preserve_default=False,
        ),
    ]
