# Generated by Django 3.2.7 on 2022-04-28 07:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('user', '0007_transaction_upiaddress'), ('user', '0008_alter_upiaddress_address'), ('user', '0009_upiaddress_unique_primaryupiaddress_user'), ('user', '0010_alter_upiaddress_is_primary')]

    dependencies = [
        ('user', '0006_alter_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('mode', models.CharField(choices=[('upi', 'UPI'), ('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('net_banking', 'Net Banking')], max_length=128, verbose_name='Mode')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount')),
                ('status', models.CharField(choices=[('failed', 'Failed'), ('success', 'Success')], max_length=128, verbose_name='Status')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='credit_transactions', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='debit_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'db_table': 'user_transaction',
            },
        ),
        migrations.CreateModel(
            name='UPIAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('address', models.CharField(max_length=128, unique=True, verbose_name='Address')),
                ('is_primary', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upi_addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'UPI Address',
                'verbose_name_plural': 'UPI Addresses',
                'db_table': 'user_upiaddress',
            },
        ),
        migrations.AddConstraint(
            model_name='upiaddress',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('user',), name='unique_primaryupiaddress_user'),
        ),
        migrations.AlterField(
            model_name='upiaddress',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
    ]
