# Generated by Django 3.2.7 on 2022-04-28 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_transaction_upiaddress_squashed_0010_alter_upiaddress_is_primary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('failed', 'Failed'), ('success', 'Success')], max_length=128, verbose_name='Status'),
        ),
    ]
